// utils/fbcookie.js
module.exports = [
    {
        "domain": ".facebook.com",
        "expirationDate": 1785652286.695658,
        "hostOnly": false,
        "httpOnly": false,
        "name": "c_user",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "100003134371797",
        "id": 1
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1787735953.13957,
        "hostOnly": false,
        "httpOnly": true,
        "name": "datr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "jVd_aJEIEWe1PEfLDzjsI1Iw",
        "id": 2
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1754721606,
        "hostOnly": false,
        "httpOnly": false,
        "name": "dpr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "0.800000011920929",
        "id": 3
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1761892286.695873,
        "hostOnly": false,
        "httpOnly": true,
        "name": "fr",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1v8ZfODaSJI83MVUm.AWfik1lNYEbzGkMVqbbyezpj2ZmD6fzYbTfFZmwBPSqu_Q3NBFk.BojbC5..AAA.0.0.BojbC5.AWeiYoaMmfnf-L0lJaASZ2vzRWM",
        "id": 4
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1785652805.943523,
        "hostOnly": false,
        "httpOnly": false,
        "name": "i_user",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "100064200486190",
        "id": 5
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1788676807.719394,
        "hostOnly": false,
        "httpOnly": true,
        "name": "ps_l",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1",
        "id": 6
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1788676807.719543,
        "hostOnly": false,
        "httpOnly": true,
        "name": "ps_n",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1",
        "id": 7
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1787735953.139714,
        "hostOnly": false,
        "httpOnly": true,
        "name": "sb",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "C2l5ZnnEjJrWG6dAap2TnYN0",
        "id": 8
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1754721095,
        "hostOnly": false,
        "httpOnly": false,
        "name": "wd",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "1705x733",
        "id": 9
    },
    {
        "domain": ".facebook.com",
        "expirationDate": 1785652286.696646,
        "hostOnly": false,
        "httpOnly": true,
        "name": "xs",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": "0",
        "value": "41%3AjOGUXk9AVSpQmg%3A2%3A1753175950%3A-1%3A-1%3A%3AAcVuQ5s2oN_EIf9g5-p8YByFgI7N9n3qiZqToNnacg",
        "id": 10
    }
    ]